apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: mileristo/api:v1
        env:
        - name: USER_NAME
          value: admin
        - name: USER_PWD
          value: password
        - name: DB_URL
          value: mongo:27017
