version: "3.1"

services:
  angular:
    image: mileristo/angular:v1
    restart: always
    ports:
      - 8000:80
  api:
    image: mileristo/api:v1
    restart: always
    ports:
      - 3000:3000
    environment:
      USER_NAME: admin
      USER_PWD: password
      DB_URL: mongo:27017
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
volumes:
  mongo-data:
    driver: local