apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  db-url: c2wk-rct.cywnblyoo1nd.eu-west-3.rds.amazonaws.com
  db_port: "3306"
  db_name: "c2wk_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: public.ecr.aws/z0b4y2d8/api:delete
          ports:
            - containerPort: 80
          env:
            - name: RCT_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user
            - name: RCT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: RCT_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db-url
            - name: RCT_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_port
            - name: RCT_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_name
            - name: NODE_ENV
              value: 'recette'
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80