# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: api-service
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: api.testsite.fr
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: api-service
#             port:
#               number: 80
# ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-service
spec:
  ingressClassName: nginx
  rules:
  - host: mileristovski.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: angular-service
            port:
              number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: service-a
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: testsite.fr
#     http:
#       paths:
#       - path: /path-a(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: service-a
#             port:
#               number: 80
# ---